theme: jekyll-theme-minimal
title: Wenhan Zhang
locale: "en-US"

logo: /Wenhan2.jpg

keywords: Homepage, CV, Academic, Wireless Communications, Machine Learning
description: Wenhan Zhang - Wireless Systems Engineer at Apple

author:
    name: Wenhan Zhang
    email: wenhanzhang@arizona.edu
    github: wenhan2020
    linkedin: https://www.linkedin.com/in/wenhan-zhang-43bb22126/

avatar: /Wenhan2.jpg

# Custom CSS
sass:
  style: compressed
