theme: jekyll-theme-minimal
title: Wenhan Zhang
locale: "en-US"

logo: /Wenhan2.jpg

keywords: Homepage, CV, Academic, Wireless Communications, Machine Learning

author:
    name: Wenhan Zhang
    email: wenhanzhang@arizona.edu
    github: wenhan2020
    linkedin: https://www.linkedin.com/in/wenhan-zhang-43bb22126/
    scholar: https://scholar.google.com/citations?user=sbC1fQsAAAAJ&hl=en

avatar: /Wenhan2.jpg

# Social Links (displayed in sidebar)
social:
  - platform: GitHub
    url: https://github.com/wenhan2020
  - platform: LinkedIn
    url: https://www.linkedin.com/in/wenhan-zhang-43bb22126/
  - platform: Email
    url: mailto:wenhanzhang@arizona.edu
  - platform: Google Scholar
    url: https://scholar.google.com/citations?user=sbC1fQsAAAAJ&hl=en

# Custom CSS
sass:
  style: compressed
